version: '3'

services:
  nginx:
    # image: nginx:1.15-alpine
    image: michele/nginx
    restart: unless-stopped
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      # - "443:443"